### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by gabrielmar** [manoelneto/star-rating#2]
Hello, I'm creating new star-rating for React and React Native and see your NPM package last updated is 7 year ago.
You could transfer the owner of the https://npmjs.com/package/star-rating to be able to publish my project.
I thank you for your attention and I would like you to consider my proposal, if you want I can send you a gif of what I'm doing in this star rating project, sorry for the inconvenience.

**Comment by manoelneto** [comment]
@GabrielMar sure, give me your npm username so I can add you as maintainer.

**Comment by gabrielmar** [comment]
gabrielmar
https://npmjs.com/~gabrielmar

**Comment by manoelneto** [comment]
Sent you invites here and in npm. Let me know if I can help you more.
